pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Cloud Kitchen UI') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no ubuntu@54.144.103.219 '
                    sudo rm -f /var/www/html/*
                '

                scp -o StrictHostKeyChecking=no index.html ubuntu@54.144.103.219:/tmp/

                ssh -o StrictHostKeyChecking=no ubuntu@<SERVER_IP> '
                    sudo mv /tmp/index.html /var/www/html/index.html
                    sudo systemctl reload nginx
                '
                """
            }
        }
    }
}
