pipeline {
  agent any

  stages {
    stage('Clone') {
      steps {
        git '<your-repo-url>'
      }
    }

    stage('Build Image') {
      steps {
        sh 'docker build -t nareshgundavelli/cloud-kitchen:latest .'
      }
    }

    stage('Push Image') {
      steps {
        sh 'docker push nareshgundavelli/cloud-kitchen:latest'
      }
    }

    stage('Deploy') {
      steps {
        sh '''
        docker rm -f cloud-kitchen || true
        docker run -d -p 80:80 --name cloud-kitchen nareshgundavelli/cloud-kitchen:latest
        '''
      }
    }
  }
}
